#!/system/bin/sh
#CPU Max Frequency
#Change CPU maximum scaling:
#2000 MHz ( WARNING ! VERY HIGH !!!)

echo "2000000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

# Display confirmation window

rm /sdcard/boeffla_twk_dlg_helper

am start -a android.intent.action.MAIN -e message "SERIOUS WARNING: On unstability resulting in reboots deselect this immediately" -e title "2 GHz CPU OC WARNING" -e okstyle "I ACKNOWLEDGE, Really :)" -n hm.agni.control.dialog.helper/.AGNiControlDialogActivity
	
while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

rm /sdcard/boeffla_twk_dlg_helper
