#!/sbin/busybox sh
#AC Charge Rate
#Set charging rate when ac charger plugged in
#2000mA

echo 2000 > /sys/devices/platform/samsung-battery/dcp_ac_input_curr
echo 2000 > /sys/devices/platform/samsung-battery/dcp_ac_chrg_curr

