#!/sbin/busybox sh
#AC Charge Rate
#Set charging rate when ac charger plugged in
#1700mA

echo 1700 > /sys/devices/platform/samsung-battery/dcp_ac_input_curr
echo 1700 > /sys/devices/platform/samsung-battery/dcp_ac_chrg_curr

