#!/sbin/busybox sh
#USB Charge Rate
#Set charging rate when connected to USB
#1200 mA (risky!)

echo 900 > /sys/devices/platform/samsung-battery/sdp_chrg_curr
echo 1200 > /sys/devices/platform/samsung-battery/cdp_chrg_curr
